### ISSUE TITLE
1000pages: Non-annotated handwritten annotation on page 0005 of "hobrecht_polytechnikum_1878"

### ISSUE THREAD

**Issue by wrznr** [OCR-D/assets#54]
![hobrecht_polytechnikum_1878_OCR-D-IMG-CROP_0005 bin](https://user-images.githubusercontent.com/26707219/64767558-2f556d00-d548-11e9-8327-b602f0259709.png)
![hobrecht_polytechnikum_1878_OCR-D-IMG-CROP_0005 dbg](https://user-images.githubusercontent.com/26707219/64767559-2fee0380-d548-11e9-956e-72e36b036403.png)

**Comment by tboenig** [comment]
fixed, see raw directory

**Comment by wrznr** [comment]
As far as I can judge, this is not yet fixed: page 0005 of hobrecht_polytechnikum_1878 in the raw directory does not contain other regions than `text` and `separator`.

**Comment by tboenig** [comment]
@wrznr I belive that's fixed.
see: https://ocr-d-repo.scc.kit.edu/api/v1/dataresources/1a0e6892-7f7f-4dcd-a740-d2e32b5c420f/data/bagit/data/OCR-D-GT-SEG-BLOCK/OCR-D-GT-SEG-BLOCK_0005.xml
https://ocr-d-repo.scc.kit.edu/api/v1/dataresources/1a0e6892-7f7f-4dcd-a740-d2e32b5c420f/data/bagit/data/OCR-D-GT-SEG-PAGE/OCR-D-GT-SEG-PAGE_0005.xml
